/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package termproject;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author sezer
 */
public class adminForm extends javax.swing.JFrame {
    private Component frame;

    /**
     * Creates new form adminForm
     */
    public adminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBarcodeNumber = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtProName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProOther = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtUserMail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUserPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUserAmount = new javax.swing.JTextField();
        btnUserSearch = new javax.swing.JButton();
        btnUserUpdate = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.blue));

        jLabel1.setText("Barcode Number ( 9 Digits )");

        txtBarcodeNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBarcodeNumber.setMaximumSize(new java.awt.Dimension(9, 9));
        txtBarcodeNumber.setMinimumSize(new java.awt.Dimension(9, 9));

        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book", "CD", "DVD" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");
        jLabel2.setToolTipText("");

        jLabel3.setText("Quantity");

        txtProQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Price");

        txtProPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtProPrice.setToolTipText("");

        jLabel5.setText("Author / Director / Artist");

        txtProOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProOtherActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setMaximumSize(new java.awt.Dimension(69, 25));
        btnUpdate.setMinimumSize(new java.awt.Dimension(69, 25));
        btnUpdate.setPreferredSize(new java.awt.Dimension(69, 25));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProOther, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBarcodeNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarcodeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtProPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtProOther))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search User Panel", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.blue));

        jLabel6.setText("User Mail");

        jLabel7.setText("User Password");

        jLabel8.setText("User Name");

        jLabel9.setText("User Phone");

        jLabel10.setText("Amount");

        btnUserSearch.setText("Search");
        btnUserSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserSearchMouseClicked(evt);
            }
        });

        btnUserUpdate.setText("Update");
        btnUserUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserUpdateMouseClicked(evt);
            }
        });

        btnClear1.setText("Clear");
        btnClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnUserSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUserUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserMail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextPane1.setEditable(false);
        jTextPane1.setText("For Product\n\nProduct Search : Enter Barcode Number and Click Search Button.\n\nAdd : Firstly, You Should Choose Product in The Combobox and Enter Barcode Number, Name, Quantity, Price and Author( for book ) / Director ( for dvd ) / Artist ( for cd ). Then You Must Click Add Button.\n\nUpdate : Firstly, You Must Use Product Search, You Should Do Necessary Regulation Without Barcode Number and Click Update Button.\n\nDelete : Firstly, You Must Use Product Search and Click Delete Button.\n\n\nFor Admin\n\nSearch : Enter User Mail and Clich Search Button\n\nUpdate : Firstly, You Must Use User Search, You Should Do Necessary Regulation Without User Mail and Click Update Button.\n\n");
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtProOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProOtherActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
       txtBarcodeNumber.setText("");
       txtBarcodeNumber.setEditable(true);
       txtProName.setText("");
       txtProName.setEditable(true);
       txtProQuantity.setText("");
       txtProQuantity.setEditable(true);
       txtProPrice.setText("");
       txtProPrice.setEditable(true);
       txtProOther.setText("");
       txtProOther.setEditable(true);
       jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        boolean anyErr = false;
        if (txtBarcodeNumber.getText().length() != 9) {
            alertError("Barcode Number Must be 9 Character");
            anyErr = true;
        }
        
        if(!anyErr && txtBarcodeNumber.getText().equalsIgnoreCase("")) {
            alertError("Barcode Number Must Not Be Empty");
            anyErr = true;
        }
        
        if (!anyErr && jComboBox1.getSelectedItem() == "Book") {
            for (int i = 0; i < TermProject.books.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.books.get(i).getBarcodeNumber())) {
                    txtBarcodeNumber.setEditable(false);
                    txtProName.setText(TermProject.books.get(i).getProductName());
                    txtProName.setEditable(false);
                    txtProQuantity.setText(Integer.toString(TermProject.books.get(i).getQuantity()));
                    txtProPrice.setText(Double.toString(TermProject.books.get(i).getPrice()));
                    txtProOther.setText(TermProject.books.get(i).getAuthor());
                    txtProOther.setEditable(false);
                }

                
            }
            
        }
        
        if (!anyErr && jComboBox1.getSelectedItem() == "DVD") {
            for (int i = 0; i < TermProject.dvds.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.dvds.get(i).getBarcodeNumber())) {
                    txtBarcodeNumber.setEditable(false);
                    txtProName.setText(TermProject.dvds.get(i).getProductName());
                    txtProName.setEditable(false);
                    txtProQuantity.setText(Integer.toString(TermProject.dvds.get(i).getQuantity()));
                    txtProPrice.setText(Double.toString(TermProject.dvds.get(i).getPrice()));
                    txtProOther.setText(TermProject.dvds.get(i).getDirector());
                    txtProOther.setEditable(false);
                }
      
            }
            
        }
        if (!anyErr && jComboBox1.getSelectedItem() == "CD") {
            for (int i = 0; i < TermProject.music.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.music.get(i).getBarcodeNumber())) {
                    txtBarcodeNumber.setEditable(false);
                    txtProName.setText(TermProject.music.get(i).getProductName());
                    txtProName.setEditable(false);
                    txtProQuantity.setText(Integer.toString(TermProject.music.get(i).getQuantity()));
                    txtProPrice.setText(Double.toString(TermProject.music.get(i).getPrice()));
                    txtProOther.setText(TermProject.music.get(i).getArtist());
                    txtProOther.setEditable(false);
                }
      
            }
            
        }
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        boolean anyErr = false;
        if (txtBarcodeNumber.getText().length() != 9) {
            alertError("Barcode Number Must be 9 Character");
            anyErr = true;
        }
        if (!anyErr && txtBarcodeNumber.getText() == "") {
            alertError("Barcode Number Shouldn't Be Empty");
            anyErr = true;
        }
        if (!anyErr && txtProName.getText() == "") {
            alertError("Product Name Shouldn't Be Empty");
            anyErr = true;
        }
        if (!anyErr && txtProQuantity.getText() == "") {
            alertError("Quantity Shouldn't Be Empty");
            anyErr = true;
        }
        if (!anyErr && txtProPrice.getText() == "") {
            alertError("Price Shouldn't Be Empty");
            anyErr = true;
        }
        if (!anyErr && txtProOther.getText() == "") {
            alertError("Author / Director / Artist Shouldn't Be Empty");
            anyErr = true;
        }
        
        if (!anyErr) {
            if (jComboBox1.getSelectedItem() == "Book") {
                boolean err = false;
                for (int i = 0; i < TermProject.books.size(); i++) {
                    if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.books.get(i).getBarcodeNumber())) {
                        err = true;
                    }
                }
                if (!err) {
                    books book = new books(txtBarcodeNumber.getText(), txtProName.getText(), txtProOther.getText(), Integer.parseInt(txtProQuantity.getText()), Double.parseDouble(txtProPrice.getText()));
                    TermProject.books.add(book);
                    Success("Adding is Success");
                } else {
                    alertError("This Barcode Number in Archieve Already");
                }
            }
            
            if (jComboBox1.getSelectedItem() == "DVD") {
                boolean err = false;
                for (int i = 0; i < TermProject.dvds.size(); i++) {
                    if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.dvds.get(i).getBarcodeNumber())) {
                        err = true;
                    }
                }
                if (!err) {
                    dvds dvd = new dvds(txtBarcodeNumber.getText(), txtProName.getText(), txtProOther.getText(), Integer.parseInt(txtProQuantity.getText()), Double.parseDouble(txtProPrice.getText()));
                    TermProject.dvds.add(dvd);
                    Success("Adding is Success");
                } else {
                    alertError("This Barcode Number in Archieve Already");
                }
            }
            
            if (jComboBox1.getSelectedItem() == "CD") {
                boolean err = false;
                for (int i = 0; i < TermProject.music.size(); i++) {
                    if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.music.get(i).getBarcodeNumber())) {
                        err = true;
                    }
                }
                if (!err) {
                    music music = new music(txtBarcodeNumber.getText(), txtProName.getText(), txtProOther.getText(), Integer.parseInt(txtProQuantity.getText()), Double.parseDouble(txtProPrice.getText()));
                    TermProject.music.add(music);
                    Success("Adding is Success");
                } else {
                    alertError("This Barcode Number in Archieve Already");
                }
            }
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        boolean anyErr = false;
        if (txtBarcodeNumber.getText().length() != 9) {
            alertError("Barcode Number Must be 9 Character");
            anyErr = true;
        }
        if (!anyErr && txtBarcodeNumber.getText() == "") {
            alertError("Barcode Number Shouldn't Be Empty");
            anyErr = true;
        }
        if (!anyErr && jComboBox1.getSelectedItem() == "Book") {
            for (int i = 0; i < TermProject.books.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.books.get(i).getBarcodeNumber())) {
                    TermProject.books.remove(i);
                    Success("Removing is Success");
                    txtBarcodeNumber.setText("");
                    txtBarcodeNumber.setEditable(true);
                    txtProName.setText("");
                    txtProName.setEditable(true);
                    txtProQuantity.setText("");
                    txtProQuantity.setEditable(true);
                    txtProPrice.setText("");
                    txtProPrice.setEditable(true);
                    txtProOther.setText("");
                    txtProOther.setEditable(true);
                    jComboBox1.setSelectedIndex(0);
                }
            }
        }
        if (!anyErr && jComboBox1.getSelectedItem() == "DVD") {
            for (int i = 0; i < TermProject.dvds.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.dvds.get(i).getBarcodeNumber())) {
                    TermProject.dvds.remove(i);
                    Success("Removing is Success");
                    txtBarcodeNumber.setText("");
                    txtBarcodeNumber.setEditable(true);
                    txtProName.setText("");
                    txtProName.setEditable(true);
                    txtProQuantity.setText("");
                    txtProQuantity.setEditable(true);
                    txtProPrice.setText("");
                    txtProPrice.setEditable(true);
                    txtProOther.setText("");
                    txtProOther.setEditable(true);
                    jComboBox1.setSelectedIndex(0);
                }
            }
        }
        if (!anyErr && jComboBox1.getSelectedItem() == "CD") {
            for (int i = 0; i < TermProject.music.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.music.get(i).getBarcodeNumber())) {
                    TermProject.music.remove(i);
                    Success("Removing is Success");
                    txtBarcodeNumber.setText("");
                    txtBarcodeNumber.setEditable(true);
                    txtProName.setText("");
                    txtProName.setEditable(true);
                    txtProQuantity.setText("");
                    txtProQuantity.setEditable(true);
                    txtProPrice.setText("");
                    txtProPrice.setEditable(true);
                    txtProOther.setText("");
                    txtProOther.setEditable(true);
                    jComboBox1.setSelectedIndex(0);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        if (jComboBox1.getSelectedItem() == "Book") {
            for (int i = 0; i < TermProject.books.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.books.get(i).getBarcodeNumber())) {
                    TermProject.books.get(i).setPrice(Double.parseDouble(txtProPrice.getText()));
                    TermProject.books.get(i).setQuantity(Integer.parseInt(txtProQuantity.getText()));
                }
            }
            Success("Updating is Successfull");
        } else if (jComboBox1.getSelectedItem() == "CD") {
            for (int i = 0; i < TermProject.music.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.music.get(i).getBarcodeNumber())) {
                    TermProject.music.get(i).setPrice(Double.parseDouble(txtProPrice.getText()));
                    TermProject.music.get(i).setQuantity(Integer.parseInt(txtProQuantity.getText()));
                }
            }
            Success("Updating is Successfull");
        } else if (jComboBox1.getSelectedItem() == "DVD") {
            for (int i = 0; i < TermProject.dvds.size(); i++) {
                if (txtBarcodeNumber.getText().equalsIgnoreCase(TermProject.dvds.get(i).getBarcodeNumber())) {
                    TermProject.dvds.get(i).setPrice(Double.parseDouble(txtProPrice.getText()));
                    TermProject.dvds.get(i).setQuantity(Integer.parseInt(txtProQuantity.getText()));
                }
            }
            Success("Updating is Successfull");
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUserSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMouseClicked
        boolean anyErr = false;
        if (txtUserMail.getText().equalsIgnoreCase("")) {
            alertError("User Mail Shouldn't Be Empty");
            anyErr = true;
        }

        if (!anyErr) {
            for (int i = 0; i < TermProject.customers.size(); i++) {
                if (txtUserMail.getText().equalsIgnoreCase(TermProject.customers.get(i).getMail())) {
                    txtUserMail.setEditable(false);
                    txtUserPassword.setText(TermProject.customers.get(i).getPassword());
                    txtUserPassword.setEditable(false);
                    txtUserName.setText(TermProject.customers.get(i).getCustomerName());
                    txtUserName.setEditable(false);
                    txtUserPhone.setText(TermProject.customers.get(i).getMobilePhone());
                    txtUserPhone.setEditable(false);
                    txtUserAmount.setText(Double.toString(TermProject.customers.get(i).getAmount()));
                }

            }

        }
    }//GEN-LAST:event_btnUserSearchMouseClicked

    private void btnUserUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserUpdateMouseClicked
        for (int i = 0; i < TermProject.customers.size(); i++) {
            if (txtUserMail.getText().equalsIgnoreCase(TermProject.customers.get(i).getMail())) {
                TermProject.customers.get(i).setAmount(Double.parseDouble(txtUserAmount.getText()));
            }
        }
        Success("Updating is Successfull");
    }//GEN-LAST:event_btnUserUpdateMouseClicked

    private void btnClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseClicked
       txtUserMail.setText("");
       txtUserMail.setEditable(true);
       txtUserPassword.setText("");
       txtUserPassword.setEditable(true);
       txtUserName.setText("");
       txtUserName.setEditable(true);
       txtUserPhone.setText("");
       txtUserPhone.setEditable(true);
       txtUserAmount.setText("");
       txtUserAmount.setEditable(true);
    }//GEN-LAST:event_btnClear1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        TermProject.LoginFrame = new LoginFrame();
        TermProject.LoginFrame.setVisible(true);
        TermProject.AdminFrame.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminForm().setVisible(true);
            }
        });
    }
    
    private void alertError(String message) {
        JOptionPane.showMessageDialog(frame,
            message,
            "Hata!",
            JOptionPane.ERROR_MESSAGE);
    }
    
    private void Success(String message) {
        JOptionPane.showMessageDialog(frame,
            message,
            "Success!",
            JOptionPane.INFORMATION_MESSAGE);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtBarcodeNumber;
    private javax.swing.JTextField txtProName;
    private javax.swing.JTextField txtProOther;
    private javax.swing.JTextField txtProPrice;
    private javax.swing.JTextField txtProQuantity;
    private javax.swing.JTextField txtUserAmount;
    private javax.swing.JTextField txtUserMail;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserPassword;
    private javax.swing.JTextField txtUserPhone;
    // End of variables declaration//GEN-END:variables
}
