/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package termproject;

import java.awt.Component;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sezer
 */
public class customerForm extends javax.swing.JFrame {
    private Component frame;

    public customerForm() {
        initComponents();
        
        Date dt = new Date();
        
        jLabel9.setText(dt.toString());

        String dizim[][] = new String[TermProject.books.size()][5];
        for (int i = 0; i < TermProject.books.size(); i++) {
            dizim[i] = new String[]{
                TermProject.books.get(i).getBarcodeNumber(),
                TermProject.books.get(i).getAuthor(),
                TermProject.books.get(i).getProductName(),
                Integer.toString(TermProject.books.get(i).getQuantity()),
                Double.toString(TermProject.books.get(i).getPrice())
            };
        }

        TableModel tabloModeli = new DefaultTableModel(dizim, new String[]{"B. Number", "Author/Director/Artist", "Name", "Quantity", "Price"});
        jTable1.setModel(tabloModeli);
        
        jLabel5.setText(TermProject.customer.getMail());
        jLabel6.setText(Double.toString(TermProject.customer.getAmount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book", "CD", "DVD" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "B. Number", "Author/Artist/Director", "Product Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Please Choose Product");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Products");

        jButton1.setText("Add to Cart");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Welcome : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Customer");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Amount");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Amount : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Enter Barcode Number");

        jButton2.setText("End Shopping");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Date");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Total Amount");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Your Shopping Cart");

        jButton3.setText("Delete Product");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel9))
                                    .addComponent(jButton3)))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        try {
            if (jComboBox1.getSelectedItem().equals("Book")) {
                String dizim[][] = new String[TermProject.books.size()][5];
                for (int i = 0; i < TermProject.books.size(); i++) {
                    dizim[i] = new String[]{
                        TermProject.books.get(i).getBarcodeNumber(),
                        TermProject.books.get(i).getAuthor(),
                        TermProject.books.get(i).getProductName(),
                        Integer.toString(TermProject.books.get(i).getQuantity()),
                        Double.toString(TermProject.books.get(i).getPrice())
                    };
                }

                TableModel tabloModeli = new DefaultTableModel(dizim, new String[]{"B. Number", "Author/Director/Artist", "Name", "Quantity", "Price"});
                jTable1.setModel(tabloModeli);
            } else if (jComboBox1.getSelectedItem().equals("CD")) {
                String dizim[][] = new String[TermProject.music.size()][5];
                for (int i = 0; i < TermProject.music.size(); i++) {
                    dizim[i] = new String[]{
                        TermProject.music.get(i).getBarcodeNumber(),
                        TermProject.music.get(i).getArtist(),
                        TermProject.music.get(i).getProductName(),
                        Integer.toString(TermProject.music.get(i).getQuantity()),
                        Double.toString(TermProject.music.get(i).getPrice())
                    };
                }

                TableModel tabloModeli = new DefaultTableModel(dizim, new String[]{"B. Number", "Author/Director/Artist", "Name", "Quantity", "Price"});
                jTable1.setModel(tabloModeli);
            } else if (jComboBox1.getSelectedItem().equals("DVD")) {
                String dizim[][] = new String[TermProject.dvds.size()][5];
                for (int i = 0; i < TermProject.dvds.size(); i++) {
                    dizim[i] = new String[]{
                        TermProject.dvds.get(i).getBarcodeNumber(),
                        TermProject.dvds.get(i).getDirector(),
                        TermProject.dvds.get(i).getProductName(),
                        Integer.toString(TermProject.dvds.get(i).getQuantity()),
                        Double.toString((TermProject.dvds.get(i).getPrice()))
                    };
                }

                TableModel tabloModeli = new DefaultTableModel(dizim, new String[]{"B. Number", "Author/Director/Artist", "Name", "Quantity", "Price"});
                jTable1.setModel(tabloModeli);
            }

        } catch (Exception e) {
            alertError("Bir Hata Oluştu");
        }


    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    double price = 0;
    DefaultListModel listModel = new DefaultListModel();
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            if (jComboBox1.getSelectedItem() == "Book") {
                for (int i = 0; i < TermProject.books.size(); i++) {
                    if (TermProject.books.get(i).getBarcodeNumber().equalsIgnoreCase(jTextField1.getText())) {
                        if (TermProject.books.get(i).getQuantity() < 1) {
                            alertError("There is not Enought Product");
                        } else {
                            TermProject.books.get(i).setQuantity(TermProject.books.get(i).getQuantity() - 1);
                            price += TermProject.books.get(i).getPrice();
                            Success("Product is Added to Shopping Cart");
                            jList1.setModel(listModel);
                            listModel.addElement(jTextField1.getText());
                            jLabel10.setText(Double.toString(price));
                            jTextField1.setText("");
                        }
                    }
                }
            }
            if (jComboBox1.getSelectedItem() == "CD") {
                for (int i = 0; i < TermProject.music.size(); i++) {
                    if (TermProject.music.get(i).getBarcodeNumber().equalsIgnoreCase(jTextField1.getText())) {
                        if (TermProject.music.get(i).getQuantity() < 1) {
                            alertError("There is not Enought Product");
                        } else {
                            TermProject.music.get(i).setQuantity(TermProject.music.get(i).getQuantity() - 1);
                            price += TermProject.music.get(i).getPrice();
                            jList1.setModel(listModel);
                            Success("Product is Added to Shopping Cart");
                            listModel.addElement(jTextField1.getText());
                            jLabel10.setText(Double.toString(price));
                            jTextField1.setText("");
                        }
                    }
                }
            }
            if (jComboBox1.getSelectedItem() == "DVD") {
                for (int i = 0; i < TermProject.dvds.size(); i++) {
                    if (TermProject.dvds.get(i).getBarcodeNumber().equalsIgnoreCase(jTextField1.getText())) {
                        if (TermProject.dvds.get(i).getQuantity() < 1) {
                            alertError("There is not Enought Product");
                        } else {
                            TermProject.dvds.get(i).setQuantity(TermProject.dvds.get(i).getQuantity() - 1);
                            price += TermProject.dvds.get(i).getPrice();
                            jList1.setModel(listModel);
                            Success("Product is Added to Shopping Cart");
                            listModel.addElement(jTextField1.getText());
                            jLabel10.setText(Double.toString(price));
                            jTextField1.setText("");
                        }
                    }
                }
            }

        } catch (Exception e) {
            alertError("Bir Hata Oluştu");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            boolean anyErr = false;
            if (price > TermProject.customer.getAmount()) {
                alertError("You don't have enough amount");
                anyErr = true;
            }
            if (!anyErr) {
                TermProject.customer.setAmount(TermProject.customer.getAmount() - price);
                Success(Double.toString(price));
                jLabel6.setText(Double.toString(TermProject.customer.getAmount()));
                jLabel10.setText(Double.toString(price));
            }
        } catch (Exception e) {
            alertError("Bir Hata Oluştu");
        }

 
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        listModel.clear();
        price = 0;
        jLabel10.setText("Total Amount");
    }//GEN-LAST:event_jButton3MouseClicked

    public static void main(String args[]) {        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerForm().setVisible(true);
            }
        });
        
    }
    
    private void Success(String message) {
        JOptionPane.showMessageDialog(frame,
            message,
            "Success!",
            JOptionPane.INFORMATION_MESSAGE);
    }
    private void alertError(String message) {
        JOptionPane.showMessageDialog(frame,
            message,
            "Hata!",
            JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
